### ISSUE TITLE
Consider using queue interprop as abstraction for queues

### ISSUE THREAD

**Issue by makasim** [apioo/fusio-adapter-amqp#1]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

**Comment by chriskapp** [comment]
Hi, looks great so, besides this AMQP adapter we have also a [Beanstalk](https://github.com/apioo/fusio-adapter-beanstalk/blob/master/src/Connection/Beanstalk.php) adapter. I could image to create a new general queue adapter which uses a specific queue interop implementation (probably php-enqueue). Of course the advantage of using a specific implementation like `php-amqplib/php-amqplib` is that you can use all AMQP specific features, which get maybe lost if you use an abstraction across multiple queues. But I will take a look at the project.

**Comment by makasim** [comment]
Thank you for the reply. 

There is [AMQP Interop](https://github.com/queue-interop/queue-interop#amqp-interop) (build on top of Queue Interop). It is set of interfaces that covers AMQP specific features, like a queue\echange declaration, binding, routing, basic.consume etc.

**Comment by chriskapp** [comment]
I will close this issue since this adapter focuses on AMQP and not a general provider.
